import type { Product } from "./types"

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "X-Burguer Especial",
    description: "Hambúrguer artesanal 180g, queijo cheddar, bacon crocante, alface e tomate",
    price: 32.9,
    image: "/gourmet-cheeseburger-bacon.png",
    category: "Lanches",
    available: true,
  },
  {
    id: "2",
    name: "Picanha na Chapa",
    description: "300g de picanha grelhada, arroz, feijão tropeiro e vinagrete",
    price: 59.9,
    image: "/grilled-steak-picanha-brazilian-style.jpg",
    category: "Pratos Principais",
    available: true,
  },
  {
    id: "3",
    name: "Frango à Parmegiana",
    description: "Filé de frango empanado, molho de tomate, queijo gratinado, arroz e fritas",
    price: 45.9,
    image: "/chicken-parmigiana-with-fries.jpg",
    category: "Pratos Principais",
    available: true,
  },
  {
    id: "4",
    name: "Refrigerante Lata",
    description: "Coca-Cola, Guaraná ou Sprite 350ml",
    price: 6.0,
    image: "/soda-can-cold-beverage.jpg",
    category: "Bebidas",
    available: true,
  },
  {
    id: "5",
    name: "Suco Natural",
    description: "Laranja, limão ou maracujá 500ml",
    price: 9.9,
    image: "/fresh-orange-juice-glass.jpg",
    category: "Bebidas",
    available: true,
  },
  {
    id: "6",
    name: "Pudim de Leite",
    description: "Pudim caseiro com calda de caramelo",
    price: 12.9,
    image: "/brazilian-pudim-flan-caramel.jpg",
    category: "Sobremesas",
    available: true,
  },
  {
    id: "7",
    name: "X-Salada",
    description: "Hambúrguer 150g, queijo, alface, tomate e maionese especial",
    price: 26.9,
    image: "/classic-cheeseburger-with-lettuce-tomato.jpg",
    category: "Lanches",
    available: true,
  },
  {
    id: "8",
    name: "Moqueca de Peixe",
    description: "Peixe fresco ao leite de coco, pimentões, arroz e pirão",
    price: 68.9,
    image: "/brazilian-moqueca-fish-stew.jpg",
    category: "Pratos Principais",
    available: false,
  },
]
